server:
  port: 8092
spring:
  r2dbc:
    url: r2dbcs:mysql://root:udemy@localhost:3306/ecommerce?serverZoneId=Asia/Jakarta&useServerPrepareStatement=true&sslMode=DISABLED&allowPublicKeyRetrieval=true
